# Generated by Django 3.1.1 on 2020-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
