# Generated by Django 3.1.1 on 2020-10-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0003_auto_20201022_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('On going', 'On going'), ('New course', 'New course'), ('To be out soon', 'To be out soon')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.DateTimeField(auto_now_add=True, choices=[('Kids 8-12 years', 'Kids 8-12 years'), ('Teenagers 13-18 years old', 'Teenagers 13-18 years old'), ('Adults older than 19', 'Adults older than 19')], null=True),
        ),
    ]
