# Generated by Django 3.1.1 on 2020-10-24 18:27

import builtins
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0005_auto_20201022_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateTimeField(null=True, verbose_name=builtins.input)),
                ('category', models.CharField(choices=[('IT Teacher', 'IT Teacher'), ('Foreign Languages Teacher', 'Foreign Languages Teacher'), ('Social Science Teacher', 'Social Science Teacher'), ('Science Teacher', 'Science Teacher')], max_length=200, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='description',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='number_of_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date_started',
            field=models.DateTimeField(null=True, verbose_name=builtins.input),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
