# Generated by Django 3.1.1 on 2020-10-24 19:05

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0006_auto_20201024_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_ended',
            field=models.DateTimeField(null=True, verbose_name=builtins.input),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='InteractiveClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_started', models.DateTimeField(null=True, verbose_name=builtins.input)),
                ('date_time_ended', models.DateTimeField(null=True, verbose_name=builtins.input)),
                ('description', models.CharField(max_length=500, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kallz_app.course')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kallz_app.professor')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kallz_app.student')),
            ],
        ),
    ]
