# Generated by Django 3.1.1 on 2020-10-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0007_auto_20201024_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
