# Generated by Django 3.1.1 on 2020-10-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0008_auto_20201024_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveclass',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kallz_app.course'),
        ),
        migrations.AlterField(
            model_name='interactiveclass',
            name='professor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kallz_app.professor'),
        ),
    ]
