# Generated by Django 3.1.1 on 2020-10-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kallz_app', '0009_auto_20201025_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveclass',
            name='students',
        ),
        migrations.AddField(
            model_name='interactiveclass',
            name='students',
            field=models.ManyToManyField(to='kallz_app.Student'),
        ),
    ]
